---
language: go
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
go:
- 1.2.2
- 1.3.1
- tip
install:
- make get
script:
- make test
after_success:
- make goveralls
env:
  global:
    secure: iSNGlDUtCd6ruDLB382WTSDq+Iyu5j1+0jhBMlxCJ0+3xYvMhTstS0v/1moE/yZF4Z/YCOIvJfnMpIUoXBNkvtBp/OeQnVCu3oW34Hzc3HIpPaps1t4RA3ufj5xB0pnu2YmIDI1VB5u59EBoze3vNjWDm5eZ+J8NSV3Q/VcYoW4=
