---
language: go
matrix:
  fast_finish: true
go:
- 1.2.2
- 1.3.1
- tip
install:
- go get -d -t ./...
- curl -sLO https://raw.githubusercontent.com/rafecolton/fmtpolice/master/fmtpolice && chmod +x fmtpolice
script:
- go test ./...
- ./fmtpolice
